@startuml

class Person{
    - name:String
    + call(Phone phone):void
}

class Phone{
    + sendMess():void
}

Person ..> Phone

note as N1
public void call(Phone phone) {
    phone.sendMess();
}
end note
Person .. N1
@enduml