@startuml

interface Subject{
 + request():void
}

class RealSubject implements Subject {
    + request():void
}

class Proxy implements Subject {
    - realSubject:RealSubject
    + request():void
    + preRequest():void
    + postRequest():void
}

Class Client {

}
Client ..> Subject

note as N1
Proxy proxy = new Proxy();
proxy.request();
end note
Client .. N1
@enduml