@startuml

class Singleton{
    - instance:Singleton
    - Singleton()
    + getInstance():Singleton
}

Singleton --o Singleton

note as N1
public static synchronized Singleton getInstance() {
    //懒汉模式实现
    if(instance == null) {
        instance = new Singleton();
    }
    return instance;
}
end note
Singleton .. N1

class Client{
    # instance:Singleton
}
@enduml