@startuml

interface Product{
 + show():void
}

interface Factory{
 + newProduct():Product
}

Factory <..> Product

class ConcreteProduct1{
    + show():void
}
class ConcreteProduct2{
    + show():void
}

ConcreteProduct1 ..^ Product
ConcreteProduct2 ..^ Product

class ConcreteFactory1{
    + newProduct():Product
}

class ConcreteFactory2{
    + newProduct():Product
}

ConcreteFactory1 ..^ Factory
ConcreteFactory2 ..^ Factory

ConcreteFactory1 ..> ConcreteProduct1
ConcreteFactory2 ..> ConcreteProduct2
@enduml